spring:
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s     # Defines a 15 s grace period
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/polardb_order
    pool:
      max-create-connection-time: 2s    # The maximum time to wait to get a connection from the pool
      initial-size: 5                   # The initial size of the connection pool
      max-size: 10                      # The maximum number of connections kept in the pool
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/polardb_order

server:
  port: 9002                            # The port where the server will accept connections
  shutdown: graceful                    # Enables graceful shutdown
  netty:
    connection-timeout: 2s              # How long to wait for a TCP connection to be established with the server
    idle-timeout: 15s                   # How long to wait before closing a TCP connection if no data is transferred

polar:
  catalog-service-uri: "http://localhost:9001"